### ISSUE TITLE
Data check tool gives error message when run

### ISSUE THREAD

**Issue by larskotthoff** [berndbischl/coseal-algsel-benchmark-repo#53]
I'm getting this when calling the data checker:

```
$ python2.7 src/main.py --dir ../data/asp-potassco/

% [WARNING]: Not found: ../data/asp-potassco/ground_truth.arff (maybe you want to add it)
% [WARNING]: Not found: ../data/asp-potassco/citation.bib (maybe you want to add it)
% Read ../data/asp-potassco/description.txt
% [WARNING]: Cannot read ALGORITHM_CUTOFF_MEMORY
% [WARNING]: Cannot read FEATURES_CUTOFF_MEMORY
% [WARNING]: Have not found algorithm_cutoff_memory
% [WARNING]: Have not found features_cutoff_memory
% [WARNING]: Have not found algorithms_stochastic
% Read ../data/asp-potassco/algorithm_runs.arff
Traceback (most recent call last):
  File "src/main.py", line 45, in <module>
    checker.main()
  File "src/main.py", line 40, in main
    instance_dict, metainfo, algo_dict = reader.parse_coseal(coseal_dir = args_.dir_, args_=args_)
  File "/home/larsko/work/coseal/data_check_tool_python/src/coseal_reader.py", line 78, in parse_coseal
    self.read_files()
  File "/home/larsko/work/coseal/data_check_tool_python/src/coseal_reader.py", line 121, in read_files
    read_func(file_)
  File "/home/larsko/work/coseal/data_check_tool_python/src/coseal_reader.py", line 255, in read_algorithm_runs
    if arff_dict["attributes"][0][0].upper() != "INSTANCE_ID":
TypeError: 'generator' object has no attribute '__getitem__'
```

I'm getting the same error when I run it on other data sets. Looking at those manually, the 'instance_id' attributes are first, so I'm not sure what the problem is here.

**Comment by mlindauer** [comment]
On my side, everything is running as I would expect it.
However, I have idea.
Unfortunately, there is another "arff" package for python. Maybe you have installed both?
Could you please run the following command in python and post the log of it:

> > > import arff
> > > arff.**doc**
> > > arff.**version**

**Comment by larskotthoff** [comment]
```
>>> import arff
>>> arff.doc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'doc'
>>> arff.version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'version'
```

**Comment by mlindauer** [comment]
arghh... the tracker absorbed the underlines. please again with two underlines.

arff.__doc

arff.__version

**Comment by larskotthoff** [comment]
Same thing. No such attribute.

**Comment by mlindauer** [comment]
what?
please try 
dir(arff)

**Comment by larskotthoff** [comment]
```
>>> dir(arff)
['ARFF_TYPES', 'ATTRIBUTE', 'COMMENT', 'DATA', 'DEFAULT_REPRS', 'GenerateRowBase', 'Nominal', 'PYTHON_TYPES', 'RELATION', 'Reader', 'SPECIAL', 'Writer', '_LineWriter', '_ParsedNominal', '_RowParser', '_SimpleType', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '_convert_row', '_csv_split', '_parse_types', '_str_remove_quotes', '_u', 'add_optional_types', 'csv', 'dump', 'dump_lines', 'dumps', 'io', 'load', 'loads', 'namedtuple', 'os']
```

**Comment by larskotthoff** [comment]
Oh and `arff.__doc__` gives me this:

```
'\nWeka arff file type reader for python.\n\nhttp://code.google.com/p/arff/\n\nhttp://code.google.com/p/arff/wiki/Documentation\n\nUsage:\n\n    >>> import arff\n    >>> for row in arff.load(\'example.arff\'):\n    ...     print(row.hair_color)\n    ...     print(row[-1])\n    ...\n    >>> print(list(arff.load(\'example.arff\')))\n    [[Row(hair_color=\'blonde\', age=17.2, patno=1),\n     Row(hair_color=\'blue\', age=27.2, patno=2),\n     Row(hair_color=\'blue\', age=18.2, patno=3)]\n\n\n\nWhere this is the example file:\n\n@relation diabetics_data\n@attribute hair_color {blonde, black, blue}\n@attribute age real\n@attribute patno integer\n@data\nblonde, 17.2, 1\nblue, 27.2, 2\nblue, 18.2, 3\n\n-----\n    >>> data = [[1,2,\'a\'], [3, 4, \'john\']]\n    >>> arff.dump(\'result.arff\', data, relation="whatever", names=[\'num\', \'day\', \'title\'])\n\nresults in the creation of this file:\n\n@relation whatever\n@attribute num integer\n@attribute day integer\n@attribute title string\n@data\n1,2,\'a\'\n3,4,\'john\'\n\n\n-----\n\n\nsupports arff types: numeric, integer, real, string\nsupports python types: int, str, float\n\nin the future: dates\n\nTested on python 2.7 and 3.2\n\nLicense: BSD, do what you wish with this. Could be awesome to hear if you found\nit useful and/or you have suggestions. ubershmekel at gmail\n\nBased on http://weka.wikispaces.com/ARFF+%28stable+version%29\n\n'
```

**Comment by mlindauer** [comment]
ok, as expected that is the wrong arff package.
I use liac-arff (see Readme).
Unfortunately, I don't know a way to choose between these two packages since they have both the same name. 
An ugly solution would be that you uninstall the wrong arff package.

**Comment by larskotthoff** [comment]
Ok, that fixed it. I promise to read the README more carefully next time.
